
modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/NovaMachina-Mods/ExNihiloSequentia-Thermal/issues" #optional
[[mods]] #mandatory
modId="exnihilothermal" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ex Nihilo: Sequentia - Thermal Expansion Addon" #mandatory
updateJSONURL="https://raw.githubusercontent.com/NovaMachina-Mods/ExNihiloSequentia-Thermal/1.16.X/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia-thermal-expansion-addon/" #optional
logoFile="" #optional
credits="" #optional
authors="NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
An addon for Ex Nihilo: Sequentia that adds support for Thermal Expansion.
'''
[[dependencies.exnihilothermal]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihilothermal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, )"
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihilothermal]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="[1.16-2.0.0.0, )"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.exnihilothermal]]
    modId="thermal"
    mandatory=true
    versionRange="[1.1.6, )"
    ordering="AFTER"
    side="BOTH"
